from dataclasses import dataclass
from datetime import datetime
from typing import List
import uuid
import json

@dataclass
class SignupRecord:
    created_at: datetime
    form_id: int
    availability: List[List[int]]
    user_id: uuid.UUID

    def __str__(self):
        return json.dumps(self.__dict__)

@dataclass
class PairRecord:
    form_id: int
    p1_id: uuid.UUID
    p2_id: uuid.UUID

    def __str__(self):
        return json.dumps(self.__dict__)

@dataclass
class FormRecord:
    id: int  # assuming it's generated by the database
    created_at: datetime

    def __str__(self):
        return json.dumps(self.__dict__)